name: bus_desktop
description: "Sistema de Monitoramento do Transporte Escolar - SEMEC"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Banco de Dados local
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  path: ^1.9.0
  path_provider: ^2.1.2

  # GPS para monitorar o ônibus
  geolocator: ^10.1.1